// Code generated by MockGen. DO NOT EDIT.
// Source: ./chains/evm/listener/handlers/rotate.go
//
// Generated by this command:
//
//	mockgen -source=./chains/evm/listener/handlers/rotate.go -destination=./mock/rotate.go -package mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	big "math/big"
	reflect "reflect"

	api "github.com/attestantio/go-eth2-client/api"
	v1 "github.com/attestantio/go-eth2-client/api/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncCommitteeFetcher is a mock of SyncCommitteeFetcher interface.
type MockSyncCommitteeFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockSyncCommitteeFetcherMockRecorder
}

// MockSyncCommitteeFetcherMockRecorder is the mock recorder for MockSyncCommitteeFetcher.
type MockSyncCommitteeFetcherMockRecorder struct {
	mock *MockSyncCommitteeFetcher
}

// NewMockSyncCommitteeFetcher creates a new mock instance.
func NewMockSyncCommitteeFetcher(ctrl *gomock.Controller) *MockSyncCommitteeFetcher {
	mock := &MockSyncCommitteeFetcher{ctrl: ctrl}
	mock.recorder = &MockSyncCommitteeFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncCommitteeFetcher) EXPECT() *MockSyncCommitteeFetcherMockRecorder {
	return m.recorder
}

// SyncCommittee mocks base method.
func (m *MockSyncCommitteeFetcher) SyncCommittee(ctx context.Context, opts *api.SyncCommitteeOpts) (*api.Response[*v1.SyncCommittee], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncCommittee", ctx, opts)
	ret0, _ := ret[0].(*api.Response[*v1.SyncCommittee])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncCommittee indicates an expected call of SyncCommittee.
func (mr *MockSyncCommitteeFetcherMockRecorder) SyncCommittee(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncCommittee", reflect.TypeOf((*MockSyncCommitteeFetcher)(nil).SyncCommittee), ctx, opts)
}

// MockPeriodStorer is a mock of PeriodStorer interface.
type MockPeriodStorer struct {
	ctrl     *gomock.Controller
	recorder *MockPeriodStorerMockRecorder
}

// MockPeriodStorerMockRecorder is the mock recorder for MockPeriodStorer.
type MockPeriodStorerMockRecorder struct {
	mock *MockPeriodStorer
}

// NewMockPeriodStorer creates a new mock instance.
func NewMockPeriodStorer(ctrl *gomock.Controller) *MockPeriodStorer {
	mock := &MockPeriodStorer{ctrl: ctrl}
	mock.recorder = &MockPeriodStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeriodStorer) EXPECT() *MockPeriodStorerMockRecorder {
	return m.recorder
}

// Period mocks base method.
func (m *MockPeriodStorer) Period(domainID uint8) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Period", domainID)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Period indicates an expected call of Period.
func (mr *MockPeriodStorerMockRecorder) Period(domainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Period", reflect.TypeOf((*MockPeriodStorer)(nil).Period), domainID)
}

// StorePeriod mocks base method.
func (m *MockPeriodStorer) StorePeriod(domainID uint8, period *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePeriod", domainID, period)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePeriod indicates an expected call of StorePeriod.
func (mr *MockPeriodStorerMockRecorder) StorePeriod(domainID, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePeriod", reflect.TypeOf((*MockPeriodStorer)(nil).StorePeriod), domainID, period)
}
